### ISSUE TITLE
Nieoptymalny kod

### ISSUE THREAD

**Issue by niooch** [wojteq18/MPiS#1]
Witam, dostrzegłem że pana kod:
`while is_more_than_one < n
        {
            let urn = rng.gen_range(0..n);
            urns[urn] = urns[urn] + 1;
            if urns[urn] == 2
            {
                is_more_than_one = is_more_than_one + 1;
            }
            additional_throwes = additional_throwes + 1;
        }`
jest **nieoptymalny**. Ile pan liczy 10^6?
Miłej niedzieli i pozdrawiam,
KK

**Comment by Siemoniere** [comment]
Zgadzam się z Panem KK. Powyższy kod jest nieoptymalny. Zalecam jego zmianę, ponieważ liczę na to, że traktuje Pan poważnie swoje studia. Zdjęcie profilowe zresztą też. W przeciwnym wypadku będę zmuszony poinformować o zaistniałej sytuacji prof. Gębalę.
Pozdrawiam i życzę spokojnej niedzieli,
SH
